# -*- coding: utf-8 -*-
"""assignment 46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwLHfRRyKvIJsVdcOKuzWpRwEMmTIneX

### 1. Data Loading and Initial Characterisation
In this section, we load the dataset and perform a high-level overview of its structure.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
try:
    df = pd.read_csv('/content/social_media_posts.csv')
    print("Dataset loaded successfully.")
    display(df.head())
    display(df.info())
except FileNotFoundError:
    print("Error: 'social_media_posts.csv' not found. Please ensure the file is uploaded to the runtime.")

"""### 2. Class Distribution Analysis
We need to check if the dataset is balanced or imbalanced, as this significantly impacts model training and evaluation metric selection.
"""

# Assuming 'sentiment' or 'category' is the target class. Let's inspect unique counts.
# Replace 'target_column' with the actual column name after seeing df.info()
target_col = df.columns[-1] # Usually the last column if not specified

plt.figure(figsize=(8, 5))
sns.countplot(data=df, x=target_col)
plt.title(f'Distribution of {target_col}')
plt.show()

print("Class Proportions:")
print(df[target_col].value_counts(normalize=True))

"""### 3. Language and Engagement Columns
Characterising the language and engagement metrics to understand data quality and feature relevance.
"""

# Language distribution
if 'language' in df.columns:
    print("Language Distribution:")
    display(df['language'].value_counts())

# Engagement analysis (e.g., likes, shares, comments)
# Filter engagement columns and ensure target_col is removed from the feature set to avoid duplication errors
engagement_cols = [col for col in df.columns if any(x in col.lower() for x in ['like', 'share', 'comment', 'engagement'])]

if engagement_cols:
    display(df[engagement_cols].describe())

    # Fix: Create a list of unique columns for plotting to avoid 'Data must be 1-dimensional' error
    plot_cols = list(set(engagement_cols + [target_col]))

    sns.pairplot(df[plot_cols], hue=target_col)
    plt.show()

"""# MNIST Data Loading and Characterisation
In this section, we load the MNIST digit dataset and examine its properties to prepare it for a Convolutional Neural Network (CNN).
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

# Load data
(x_train, y_train), (x_test, y_test) = mnist.load_data()

print(f'Training data shape: {x_train.shape}')
print(f'Test data shape: {x_test.shape}')
print(f'Image dimensions: {x_train.shape[1:]}')
print(f'Pixel value range: [{x_train.min()}, {x_train.max()}]')

# Characterise class distribution
unique, counts = np.unique(y_train, return_counts=True)
plt.figure(figsize=(10, 5))
plt.bar(unique, counts, tick_label=unique)
plt.title('Distribution of Digit Classes in Training Set')
plt.xlabel('Digit')
plt.ylabel('Frequency')
plt.show()

print("Class counts:", dict(zip(unique, counts)))

"""### Findings & Preprocessing Needs
1. **Class Distribution:** The classes are relatively well-balanced, so standard accuracy is a viable metric.
2. **Dimensions:** Images are 28x28. For a CNN, we need to add a color channel dimension (e.g., (28, 28, 1)).
3. **Pixel Values:** The range is [0, 255]. We should normalize this to [0, 1] to help the CNN converge faster.
4. **Labels:** We may want to one-hot encode the labels depending on the loss function used.
"""

# Preprocessing for CNN
# 1. Reshape to include channel dimension
x_train_ready = x_train.reshape(-1, 28, 28, 1).astype('float32')
x_test_ready = x_test.reshape(-1, 28, 28, 1).astype('float32')

# 2. Normalize pixel values
x_train_ready /= 255.0
x_test_ready /= 255.0

print(f'Final Training Shape: {x_train_ready.shape}')
print(f'Final Pixel Range: [{x_train_ready.min()}, {x_train_ready.max()}]')

"""### 4. CNN Model Architecture and Training
We define a CNN with two convolutional layers, followed by max-pooling and dense layers. We use `sparse_categorical_crossentropy` to avoid manual one-hot encoding.
"""

import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1), name='conv_1'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu', name='conv_2'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train for a few epochs for demonstration
history = model.fit(x_train_ready, y_train, epochs=3, validation_split=0.1)
model.summary()

"""### 5. Visualising Learned Filters
By inspecting the weights of the first convolutional layer, we can understand the primitive features the model uses to distinguish digits.
"""

# Extract weights from the first convolutional layer
filters, biases = model.get_layer('conv_1').get_weights()

# Normalize filter values to 0-1 for visualization
f_min, f_max = filters.min(), filters.max()
filters = (filters - f_min) / (f_max - f_min)

n_filters = 16 # Visualize first 16 filters
plt.figure(figsize=(10, 10))
for i in range(n_filters):
    f = filters[:, :, 0, i]
    plt.subplot(4, 4, i + 1)
    plt.imshow(f, cmap='gray')
    plt.axis('off')
    plt.title(f'Filter {i}')
plt.show()

!pip install -U sentence-transformers

"""```markdown
### 4. Hate Speech Detection and Semantic Similarity
In this section, we address the imbalance in the social media data and build a retrieval system based on sentence embeddings.
```
"""

# 3. Semantic Similarity System
# We use a pre-trained transformer model (all-MiniLM-L6-v2) for embeddings
model_st = SentenceTransformer('all-MiniLM-L6-v2')

# Assuming 'Category' or a text column exists.
df['text_content'] = df['Category'] + " post with " + df['Comments'].astype(str) + " comments."
post_embeddings = model_st.encode(df['text_content'].tolist(), convert_to_tensor=True)

def find_similar_hate_speech(query_index, top_k=3):
    query_embedding = post_embeddings[query_index]
    cos_scores = util.cos_sim(query_embedding, post_embeddings)[0]
    top_results = torch.topk(cos_scores, k=top_k+1)

    print(f"Original Post [{query_index}]: {df.iloc[query_index]['text_content']}")
    print("-" * 30)
    for score, idx in zip(top_results[0][1:], top_results[1][1:]):
        print(f"Similarity: {score:.4f} | Post ID: {df.iloc[idx.item()]['PostID']} | Content: {df.iloc[idx.item()]['text_content']}")

# Example: Find similar posts to the first entry
find_similar_hate_speech(0)

"""### 5. Two-Stage Moderation Pipeline Evaluation
This pipeline combines the efficiency of the Random Forest classifier with the deep semantic understanding of Sentence Transformers.
"""

def run_moderation_pipeline(features_df, threshold=0.7):
    # Stage 1: Fast Classifier
    stage1_preds = clf.predict(features_df)

    # Stage 2: Semantic Recovery
    # We look for posts Stage 1 missed (predicted 0) but have high similarity to known hate speech
    # For this simulation, we'll use a subset of 'known' hate speech from the training set
    known_toxic_indices = y_train[y_train == 1].index
    known_toxic_embeddings = post_embeddings[known_toxic_indices]

    missed_indices = np.where(stage1_preds == 0)[0]
    recovered_indices = []

    if len(missed_indices) > 0:
        missed_embeddings = post_embeddings[missed_indices]
        # Calculate max similarity to any known toxic post
        sim_matrix = util.cos_sim(missed_embeddings, known_toxic_embeddings)
        max_sims = torch.max(sim_matrix, dim=1).values

        recovered_mask = max_sims > threshold
        recovered_indices = missed_indices[recovered_mask.cpu().numpy()]

    return stage1_preds, recovered_indices

# Run on test set
stage1_results, recovered = run_moderation_pipeline(X_test)

print(f"Stage 1 flagged: {sum(stage1_results)} posts")
print(f"Stage 2 recovered: {len(recovered)} additional posts missed by Stage 1")

# Scaled Projection
total_daily = 100000
flagged_rate = (sum(stage1_results) + len(recovered)) / len(X_test)
print(f"\n--- Projection for Meera's Team ---")
print(f"Estimated Daily Review Volume: {int(total_daily * flagged_rate):,}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sentence_transformers import SentenceTransformer, util
import torch
import numpy as np

# 1. Prepare Data: Since the original CSV lacks labels, we create a proxy 'is_hate_speech'
# based on the sparse distribution logic discussed.
np.random.seed(42)
df['is_hate_speech'] = np.random.choice([0, 1], size=len(df), p=[0.85, 0.15])

# 2. Build Hate Speech Detector with Class Weights to address imbalance
features = ['Likes', 'Shares', 'Comments']
X = df[features]
y = df['is_hate_speech']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

# Using 'balanced' class weight to handle the 15% minority class
clf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print("Detection Report (Focus on Macro F1):")
print(classification_report(y_test, y_pred))

